# -*- coding: utf-8 -*-
"""cancer_predic_DecisionTree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1THsskiYqML_2db5Avm47-6wCozLNWKgj
"""

from sklearn.datasets import load_breast_cancer              # Loading the IRIS flower datasets
import matplotlib.pyplot as plt                     # Graph plotting library
from sklearn.tree import DecisionTreeClassifier     # Calling DecisionTreeClassifier Algorithm for training
from sklearn.metrics import accuracy_score         # To find the accuracy score

bc=load_breast_cancer()

dir(bc)

features=bc.data
label=bc.target

# Splitting Training and Testing data 90:10
from sklearn.model_selection import train_test_split

train_data,test_data,label_train,label_test=train_test_split(features,label,test_size=0.1)

# Calling Decision Tree CLassifier
clf=DecisionTreeClassifier()

# Training the data
trained=clf.fit(train_data,label_train)

# Predicting the data
predicted=trained.predict(test_data)

# Predicted Output
predicted

# Acutal Output
label_test

# Accuracy Score
accuracy_score(label_test,predicted)

