# -*- coding: utf-8 -*-
"""SupportVectorCLF_on_digits.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B2xOYakJ_Vyk1RDlTc6YrNxt0aNM4EDl
"""

from sklearn.datasets import load_digits

# Loading Digit data
digit=load_digits()

dir(digit)

# Fetching feature and labels
features=digit.data
label=digit.target

# Splitting the data into training and testing..
from sklearn.model_selection import train_test_split
train_data,test_data,train_label,test_label=train_test_split(features,label,test_size=0.1)

# Visualizing data
import matplotlib.pyplot as plt
plt.imshow(digit.images[0])

# Now calling Support Vector Classifier (SVC)
from sklearn.svm import SVC
clf=SVC()

# Training the data
trained=clf.fit(train_data,train_label)

# Predicting the output
predicted=trained.predict(test_data)

predicted

test_label

from sklearn.metrics import accuracy_score
accuracy_score(predicted,test_label)

